version: '3.7'
services:
  postgres:
    image: postgres:14
    container_name: postgres_db
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ai-chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
