version: '3.7'
services:
  postgres:
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ai-chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  redis:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 30s
      retries: 3
