version: '3.7'
services:
  postgres:
    image: postgres:14
    ports:
      - '5433:5432'
    environment:
      POSTGRES_DB: ai-chatbot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
