name: 'Dev Deployment'

on:
  push:
    branches:
      - dev

env:
  NAME: blox3-v1-prod
  ZONE: asia-southeast1-a
  SVC_NAME: ai-chatbot-api
  IMAGE_REPO: ${{ vars.ECR_URL }}/ai-chatbot-api-dev

jobs:
  build-deploy:
    name: Build and deploy application to server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.MY_REPO_PAT_NEW }}

      # - name: Build Docker
      #   run: |
      #     docker build -t ${{ env.IMAGE_REPO }}:latest .

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_NEW }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_NEW }}
      #     aws-region: ap-southeast-1

      # - name: Login to Amazon ECR
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      # - name: Upload to ECR
      #   run: |
      #     docker push $IMAGE_REPO:latest

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.DEPLOY_SERVER }}
          port: ${{ vars.SSH_PORT }}
          username: ${{vars.SSH_USER}}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/massbit/heydevs_dev/ai-chatbot-api
            git checkout dev
            git pull
            npm run build
            pm2 restart ai-chatbot-api --update-env
