export enum Persona {
  FRIENDLY = 'friendly',
  FORMAL = 'formal',
  CASUAL = 'casual',
  PROFESSIONAL = 'professional',
  HUMOROUS = 'humorous',
  SYMPATHETIC = 'sympathetic',
  ENCOURAGING = 'encouraging',
  NEUTRAL = 'neutral',
  DIRECT = 'direct',
}

export enum Instruction {
  LimitSentences = 'Keep your answers under 3 sentences.',
  ProvideCustomerSupport = 'Provide customer support',
  HandleBillingSupport = 'Handle billing support',
  ManageAccountSupport = 'Manage account support',
  OfferTechnicalSupport = 'Offer technical support',
  ResolveSoftwareIssues = 'Resolve software issues',
  FixHardwareIssues = 'Fix hardware issues',
  AnswerProductInquiries = 'Answer product inquiries',
  CheckProductAvailability = 'Check product availability',
  ExplainProductFeatures = 'Explain product features',
  ProvideSalesSupport = 'Provide sales support',
  ProcessNewOrders = 'Process new orders',
  UpdateOrderStatus = 'Update order status',
  HandleReturnsAndExchanges = 'Handle returns and exchanges',
  ProvideShippingInfo = 'Provide shipping information',
  HandleOtherRequests = 'Handle other requests',
}
